/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Billing service. Represents a row in the &quot;SPHMS_Billing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sphms.common.service.model.impl.BillingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sphms.common.service.model.impl.BillingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Billing
 * @see com.sphms.common.service.model.impl.BillingImpl
 * @see com.sphms.common.service.model.impl.BillingModelImpl
 * @generated
 */
@ProviderType
public interface BillingModel extends BaseModel<Billing> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a billing model instance should use the {@link Billing} interface instead.
	 */

	/**
	 * Returns the primary key of this billing.
	 *
	 * @return the primary key of this billing
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this billing.
	 *
	 * @param primaryKey the primary key of this billing
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the billing ID of this billing.
	 *
	 * @return the billing ID of this billing
	 */
	public long getBillingId();

	/**
	 * Sets the billing ID of this billing.
	 *
	 * @param billingId the billing ID of this billing
	 */
	public void setBillingId(long billingId);

	/**
	 * Returns the custom company ID of this billing.
	 *
	 * @return the custom company ID of this billing
	 */
	public long getCustomCompanyId();

	/**
	 * Sets the custom company ID of this billing.
	 *
	 * @param customCompanyId the custom company ID of this billing
	 */
	public void setCustomCompanyId(long customCompanyId);

	/**
	 * Returns the bill no of this billing.
	 *
	 * @return the bill no of this billing
	 */
	@AutoEscape
	public String getBillNo();

	/**
	 * Sets the bill no of this billing.
	 *
	 * @param billNo the bill no of this billing
	 */
	public void setBillNo(String billNo);

	/**
	 * Returns the internal bill no of this billing.
	 *
	 * @return the internal bill no of this billing
	 */
	@AutoEscape
	public String getInternalBillNo();

	/**
	 * Sets the internal bill no of this billing.
	 *
	 * @param internalBillNo the internal bill no of this billing
	 */
	public void setInternalBillNo(String internalBillNo);

	/**
	 * Returns the booking ID of this billing.
	 *
	 * @return the booking ID of this billing
	 */
	public long getBookingId();

	/**
	 * Sets the booking ID of this billing.
	 *
	 * @param bookingId the booking ID of this billing
	 */
	public void setBookingId(long bookingId);

	/**
	 * Returns the client ID of this billing.
	 *
	 * @return the client ID of this billing
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this billing.
	 *
	 * @param clientId the client ID of this billing
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the bill file entry ID of this billing.
	 *
	 * @return the bill file entry ID of this billing
	 */
	public long getBillFileEntryId();

	/**
	 * Sets the bill file entry ID of this billing.
	 *
	 * @param billFileEntryId the bill file entry ID of this billing
	 */
	public void setBillFileEntryId(long billFileEntryId);

	/**
	 * Returns the client p a n no of this billing.
	 *
	 * @return the client p a n no of this billing
	 */
	@AutoEscape
	public String getClientPANNo();

	/**
	 * Sets the client p a n no of this billing.
	 *
	 * @param clientPANNo the client p a n no of this billing
	 */
	public void setClientPANNo(String clientPANNo);

	/**
	 * Returns the client p o number of this billing.
	 *
	 * @return the client p o number of this billing
	 */
	@AutoEscape
	public String getClientPONumber();

	/**
	 * Sets the client p o number of this billing.
	 *
	 * @param clientPONumber the client p o number of this billing
	 */
	public void setClientPONumber(String clientPONumber);

	/**
	 * Returns the client g s t number of this billing.
	 *
	 * @return the client g s t number of this billing
	 */
	@AutoEscape
	public String getClientGSTNumber();

	/**
	 * Sets the client g s t number of this billing.
	 *
	 * @param clientGSTNumber the client g s t number of this billing
	 */
	public void setClientGSTNumber(String clientGSTNumber);

	/**
	 * Returns the display of this billing.
	 *
	 * @return the display of this billing
	 */
	@AutoEscape
	public String getDisplay();

	/**
	 * Sets the display of this billing.
	 *
	 * @param display the display of this billing
	 */
	public void setDisplay(String display);

	/**
	 * Returns the access amount of this billing.
	 *
	 * @return the access amount of this billing
	 */
	public double getAccessAmount();

	/**
	 * Sets the access amount of this billing.
	 *
	 * @param accessAmount the access amount of this billing
	 */
	public void setAccessAmount(double accessAmount);

	/**
	 * Returns the pending amount of this billing.
	 *
	 * @return the pending amount of this billing
	 */
	public double getPendingAmount();

	/**
	 * Sets the pending amount of this billing.
	 *
	 * @param pendingAmount the pending amount of this billing
	 */
	public void setPendingAmount(double pendingAmount);

	/**
	 * Returns the financial year of this billing.
	 *
	 * @return the financial year of this billing
	 */
	@AutoEscape
	public String getFinancialYear();

	/**
	 * Sets the financial year of this billing.
	 *
	 * @param financialYear the financial year of this billing
	 */
	public void setFinancialYear(String financialYear);

	/**
	 * Returns the status of this billing.
	 *
	 * @return the status of this billing
	 */
	public int getStatus();

	/**
	 * Sets the status of this billing.
	 *
	 * @param status the status of this billing
	 */
	public void setStatus(int status);

	/**
	 * Returns the publish date of this billing.
	 *
	 * @return the publish date of this billing
	 */
	public Date getPublishDate();

	/**
	 * Sets the publish date of this billing.
	 *
	 * @param publishDate the publish date of this billing
	 */
	public void setPublishDate(Date publishDate);

	/**
	 * Returns the create date of this billing.
	 *
	 * @return the create date of this billing
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this billing.
	 *
	 * @param createDate the create date of this billing
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this billing.
	 *
	 * @return the created by of this billing
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this billing.
	 *
	 * @param createdBy the created by of this billing
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this billing.
	 *
	 * @return the modified date of this billing
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this billing.
	 *
	 * @param modifiedDate the modified date of this billing
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this billing.
	 *
	 * @return the modified by of this billing
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this billing.
	 *
	 * @param modifiedBy the modified by of this billing
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Billing billing);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Billing> toCacheModel();

	@Override
	public Billing toEscapedModel();

	@Override
	public Billing toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}