/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import com.sphms.common.service.service.persistence.Booking_HordingPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Booking_Hording service. Represents a row in the &quot;SPHMS_Booking_Hording&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sphms.common.service.model.impl.Booking_HordingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sphms.common.service.model.impl.Booking_HordingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Booking_Hording
 * @see com.sphms.common.service.model.impl.Booking_HordingImpl
 * @see com.sphms.common.service.model.impl.Booking_HordingModelImpl
 * @generated
 */
@ProviderType
public interface Booking_HordingModel extends BaseModel<Booking_Hording> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a booking_ hording model instance should use the {@link Booking_Hording} interface instead.
	 */

	/**
	 * Returns the primary key of this booking_ hording.
	 *
	 * @return the primary key of this booking_ hording
	 */
	public Booking_HordingPK getPrimaryKey();

	/**
	 * Sets the primary key of this booking_ hording.
	 *
	 * @param primaryKey the primary key of this booking_ hording
	 */
	public void setPrimaryKey(Booking_HordingPK primaryKey);

	/**
	 * Returns the booking ID of this booking_ hording.
	 *
	 * @return the booking ID of this booking_ hording
	 */
	public long getBookingId();

	/**
	 * Sets the booking ID of this booking_ hording.
	 *
	 * @param bookingId the booking ID of this booking_ hording
	 */
	public void setBookingId(long bookingId);

	/**
	 * Returns the hording ID of this booking_ hording.
	 *
	 * @return the hording ID of this booking_ hording
	 */
	public long getHordingId();

	/**
	 * Sets the hording ID of this booking_ hording.
	 *
	 * @param hordingId the hording ID of this booking_ hording
	 */
	public void setHordingId(long hordingId);

	/**
	 * Returns the mounting charge of this booking_ hording.
	 *
	 * @return the mounting charge of this booking_ hording
	 */
	public double getMountingCharge();

	/**
	 * Sets the mounting charge of this booking_ hording.
	 *
	 * @param mountingCharge the mounting charge of this booking_ hording
	 */
	public void setMountingCharge(double mountingCharge);

	/**
	 * Returns the printing charge of this booking_ hording.
	 *
	 * @return the printing charge of this booking_ hording
	 */
	public double getPrintingCharge();

	/**
	 * Sets the printing charge of this booking_ hording.
	 *
	 * @param printingCharge the printing charge of this booking_ hording
	 */
	public void setPrintingCharge(double printingCharge);

	/**
	 * Returns the units of this booking_ hording.
	 *
	 * @return the units of this booking_ hording
	 */
	public int getUnits();

	/**
	 * Sets the units of this booking_ hording.
	 *
	 * @param units the units of this booking_ hording
	 */
	public void setUnits(int units);

	/**
	 * Returns the hsn no of this booking_ hording.
	 *
	 * @return the hsn no of this booking_ hording
	 */
	@AutoEscape
	public String getHsnNo();

	/**
	 * Sets the hsn no of this booking_ hording.
	 *
	 * @param hsnNo the hsn no of this booking_ hording
	 */
	public void setHsnNo(String hsnNo);

	/**
	 * Returns the hording booking start date of this booking_ hording.
	 *
	 * @return the hording booking start date of this booking_ hording
	 */
	public Date getHordingBookingStartDate();

	/**
	 * Sets the hording booking start date of this booking_ hording.
	 *
	 * @param hordingBookingStartDate the hording booking start date of this booking_ hording
	 */
	public void setHordingBookingStartDate(Date hordingBookingStartDate);

	/**
	 * Returns the hording booking end date of this booking_ hording.
	 *
	 * @return the hording booking end date of this booking_ hording
	 */
	public Date getHordingBookingEndDate();

	/**
	 * Sets the hording booking end date of this booking_ hording.
	 *
	 * @param hordingBookingEndDate the hording booking end date of this booking_ hording
	 */
	public void setHordingBookingEndDate(Date hordingBookingEndDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Booking_Hording booking_Hording);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Booking_Hording> toCacheModel();

	@Override
	public Booking_Hording toEscapedModel();

	@Override
	public Booking_Hording toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}