/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Client service. Represents a row in the &quot;SPHMS_Client&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sphms.common.service.model.impl.ClientModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sphms.common.service.model.impl.ClientImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Client
 * @see com.sphms.common.service.model.impl.ClientImpl
 * @see com.sphms.common.service.model.impl.ClientModelImpl
 * @generated
 */
@ProviderType
public interface ClientModel extends BaseModel<Client> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a client model instance should use the {@link Client} interface instead.
	 */

	/**
	 * Returns the primary key of this client.
	 *
	 * @return the primary key of this client
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this client.
	 *
	 * @param primaryKey the primary key of this client
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the client ID of this client.
	 *
	 * @return the client ID of this client
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this client.
	 *
	 * @param clientId the client ID of this client
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the client name of this client.
	 *
	 * @return the client name of this client
	 */
	@AutoEscape
	public String getClientName();

	/**
	 * Sets the client name of this client.
	 *
	 * @param clientName the client name of this client
	 */
	public void setClientName(String clientName);

	/**
	 * Returns the address1 of this client.
	 *
	 * @return the address1 of this client
	 */
	@AutoEscape
	public String getAddress1();

	/**
	 * Sets the address1 of this client.
	 *
	 * @param address1 the address1 of this client
	 */
	public void setAddress1(String address1);

	/**
	 * Returns the address2 of this client.
	 *
	 * @return the address2 of this client
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this client.
	 *
	 * @param address2 the address2 of this client
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this client.
	 *
	 * @return the city of this client
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this client.
	 *
	 * @param city the city of this client
	 */
	public void setCity(String city);

	/**
	 * Returns the pan no of this client.
	 *
	 * @return the pan no of this client
	 */
	@AutoEscape
	public String getPanNo();

	/**
	 * Sets the pan no of this client.
	 *
	 * @param panNo the pan no of this client
	 */
	public void setPanNo(String panNo);

	/**
	 * Returns the gst no of this client.
	 *
	 * @return the gst no of this client
	 */
	@AutoEscape
	public String getGstNo();

	/**
	 * Sets the gst no of this client.
	 *
	 * @param gstNo the gst no of this client
	 */
	public void setGstNo(String gstNo);

	/**
	 * Returns the state of this client.
	 *
	 * @return the state of this client
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this client.
	 *
	 * @param state the state of this client
	 */
	public void setState(String state);

	/**
	 * Returns the contact person name of this client.
	 *
	 * @return the contact person name of this client
	 */
	@AutoEscape
	public String getContactPersonName();

	/**
	 * Sets the contact person name of this client.
	 *
	 * @param contactPersonName the contact person name of this client
	 */
	public void setContactPersonName(String contactPersonName);

	/**
	 * Returns the contact person email of this client.
	 *
	 * @return the contact person email of this client
	 */
	@AutoEscape
	public String getContactPersonEmail();

	/**
	 * Sets the contact person email of this client.
	 *
	 * @param contactPersonEmail the contact person email of this client
	 */
	public void setContactPersonEmail(String contactPersonEmail);

	/**
	 * Returns the contact person phone no of this client.
	 *
	 * @return the contact person phone no of this client
	 */
	@AutoEscape
	public String getContactPersonPhoneNo();

	/**
	 * Sets the contact person phone no of this client.
	 *
	 * @param contactPersonPhoneNo the contact person phone no of this client
	 */
	public void setContactPersonPhoneNo(String contactPersonPhoneNo);

	/**
	 * Returns the create date of this client.
	 *
	 * @return the create date of this client
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this client.
	 *
	 * @param createDate the create date of this client
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this client.
	 *
	 * @return the created by of this client
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this client.
	 *
	 * @param createdBy the created by of this client
	 */
	public void setCreatedBy(long createdBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Client client);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Client> toCacheModel();

	@Override
	public Client toEscapedModel();

	@Override
	public Client toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}