/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CreditNote service. Represents a row in the &quot;SPHMS_CreditNote&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sphms.common.service.model.impl.CreditNoteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sphms.common.service.model.impl.CreditNoteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CreditNote
 * @see com.sphms.common.service.model.impl.CreditNoteImpl
 * @see com.sphms.common.service.model.impl.CreditNoteModelImpl
 * @generated
 */
@ProviderType
public interface CreditNoteModel extends BaseModel<CreditNote> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a credit note model instance should use the {@link CreditNote} interface instead.
	 */

	/**
	 * Returns the primary key of this credit note.
	 *
	 * @return the primary key of this credit note
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this credit note.
	 *
	 * @param primaryKey the primary key of this credit note
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the credit note ID of this credit note.
	 *
	 * @return the credit note ID of this credit note
	 */
	public long getCreditNoteId();

	/**
	 * Sets the credit note ID of this credit note.
	 *
	 * @param creditNoteId the credit note ID of this credit note
	 */
	public void setCreditNoteId(long creditNoteId);

	/**
	 * Returns the client ID of this credit note.
	 *
	 * @return the client ID of this credit note
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this credit note.
	 *
	 * @param clientId the client ID of this credit note
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the billing ID of this credit note.
	 *
	 * @return the billing ID of this credit note
	 */
	public long getBillingId();

	/**
	 * Sets the billing ID of this credit note.
	 *
	 * @param billingId the billing ID of this credit note
	 */
	public void setBillingId(long billingId);

	/**
	 * Returns the credit note number of this credit note.
	 *
	 * @return the credit note number of this credit note
	 */
	@AutoEscape
	public String getCreditNoteNumber();

	/**
	 * Sets the credit note number of this credit note.
	 *
	 * @param creditNoteNumber the credit note number of this credit note
	 */
	public void setCreditNoteNumber(String creditNoteNumber);

	/**
	 * Returns the credit note amount of this credit note.
	 *
	 * @return the credit note amount of this credit note
	 */
	public double getCreditNoteAmount();

	/**
	 * Sets the credit note amount of this credit note.
	 *
	 * @param creditNoteAmount the credit note amount of this credit note
	 */
	public void setCreditNoteAmount(double creditNoteAmount);

	/**
	 * Returns the credit note tax of this credit note.
	 *
	 * @return the credit note tax of this credit note
	 */
	public double getCreditNoteTax();

	/**
	 * Sets the credit note tax of this credit note.
	 *
	 * @param creditNoteTax the credit note tax of this credit note
	 */
	public void setCreditNoteTax(double creditNoteTax);

	/**
	 * Returns the payment date of this credit note.
	 *
	 * @return the payment date of this credit note
	 */
	public Date getPaymentDate();

	/**
	 * Sets the payment date of this credit note.
	 *
	 * @param paymentDate the payment date of this credit note
	 */
	public void setPaymentDate(Date paymentDate);

	/**
	 * Returns the cheque no of this credit note.
	 *
	 * @return the cheque no of this credit note
	 */
	@AutoEscape
	public String getChequeNo();

	/**
	 * Sets the cheque no of this credit note.
	 *
	 * @param chequeNo the cheque no of this credit note
	 */
	public void setChequeNo(String chequeNo);

	/**
	 * Returns the bank name of this credit note.
	 *
	 * @return the bank name of this credit note
	 */
	@AutoEscape
	public String getBankName();

	/**
	 * Sets the bank name of this credit note.
	 *
	 * @param bankName the bank name of this credit note
	 */
	public void setBankName(String bankName);

	/**
	 * Returns the financial year of this credit note.
	 *
	 * @return the financial year of this credit note
	 */
	@AutoEscape
	public String getFinancialYear();

	/**
	 * Sets the financial year of this credit note.
	 *
	 * @param financialYear the financial year of this credit note
	 */
	public void setFinancialYear(String financialYear);

	/**
	 * Returns the create date of this credit note.
	 *
	 * @return the create date of this credit note
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this credit note.
	 *
	 * @param createDate the create date of this credit note
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this credit note.
	 *
	 * @return the created by of this credit note
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this credit note.
	 *
	 * @param createdBy the created by of this credit note
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this credit note.
	 *
	 * @return the modified date of this credit note
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this credit note.
	 *
	 * @param modifiedDate the modified date of this credit note
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this credit note.
	 *
	 * @return the modified by of this credit note
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this credit note.
	 *
	 * @param modifiedBy the modified by of this credit note
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CreditNote creditNote);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CreditNote> toCacheModel();

	@Override
	public CreditNote toEscapedModel();

	@Override
	public CreditNote toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}