/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CustomCompany service. Represents a row in the &quot;SPHMS_CustomCompany&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sphms.common.service.model.impl.CustomCompanyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sphms.common.service.model.impl.CustomCompanyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomCompany
 * @see com.sphms.common.service.model.impl.CustomCompanyImpl
 * @see com.sphms.common.service.model.impl.CustomCompanyModelImpl
 * @generated
 */
@ProviderType
public interface CustomCompanyModel extends BaseModel<CustomCompany>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom company model instance should use the {@link CustomCompany} interface instead.
	 */

	/**
	 * Returns the primary key of this custom company.
	 *
	 * @return the primary key of this custom company
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom company.
	 *
	 * @param primaryKey the primary key of this custom company
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company ID of this custom company.
	 *
	 * @return the company ID of this custom company
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this custom company.
	 *
	 * @param companyId the company ID of this custom company
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this custom company.
	 *
	 * @return the name of this custom company
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this custom company.
	 *
	 * @param name the name of this custom company
	 */
	public void setName(String name);

	/**
	 * Returns the g s t no of this custom company.
	 *
	 * @return the g s t no of this custom company
	 */
	@AutoEscape
	public String getGSTNo();

	/**
	 * Sets the g s t no of this custom company.
	 *
	 * @param GSTNo the g s t no of this custom company
	 */
	public void setGSTNo(String GSTNo);

	/**
	 * Returns the p a n no of this custom company.
	 *
	 * @return the p a n no of this custom company
	 */
	@AutoEscape
	public String getPANNo();

	/**
	 * Sets the p a n no of this custom company.
	 *
	 * @param PANNo the p a n no of this custom company
	 */
	public void setPANNo(String PANNo);

	/**
	 * Returns the bank name of this custom company.
	 *
	 * @return the bank name of this custom company
	 */
	@AutoEscape
	public String getBankName();

	/**
	 * Sets the bank name of this custom company.
	 *
	 * @param bankName the bank name of this custom company
	 */
	public void setBankName(String bankName);

	/**
	 * Returns the account detail of this custom company.
	 *
	 * @return the account detail of this custom company
	 */
	@AutoEscape
	public String getAccountDetail();

	/**
	 * Sets the account detail of this custom company.
	 *
	 * @param accountDetail the account detail of this custom company
	 */
	public void setAccountDetail(String accountDetail);

	/**
	 * Returns the po prefix of this custom company.
	 *
	 * @return the po prefix of this custom company
	 */
	@AutoEscape
	public String getPoPrefix();

	/**
	 * Sets the po prefix of this custom company.
	 *
	 * @param poPrefix the po prefix of this custom company
	 */
	public void setPoPrefix(String poPrefix);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CustomCompany customCompany);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CustomCompany> toCacheModel();

	@Override
	public CustomCompany toEscapedModel();

	@Override
	public CustomCompany toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}