/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Expense service. Represents a row in the &quot;SPHMS_Expense&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sphms.common.service.model.impl.ExpenseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sphms.common.service.model.impl.ExpenseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Expense
 * @see com.sphms.common.service.model.impl.ExpenseImpl
 * @see com.sphms.common.service.model.impl.ExpenseModelImpl
 * @generated
 */
@ProviderType
public interface ExpenseModel extends BaseModel<Expense> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a expense model instance should use the {@link Expense} interface instead.
	 */

	/**
	 * Returns the primary key of this expense.
	 *
	 * @return the primary key of this expense
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this expense.
	 *
	 * @param primaryKey the primary key of this expense
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the expense ID of this expense.
	 *
	 * @return the expense ID of this expense
	 */
	public long getExpenseId();

	/**
	 * Sets the expense ID of this expense.
	 *
	 * @param expenseId the expense ID of this expense
	 */
	public void setExpenseId(long expenseId);

	/**
	 * Returns the custom company ID of this expense.
	 *
	 * @return the custom company ID of this expense
	 */
	public long getCustomCompanyId();

	/**
	 * Sets the custom company ID of this expense.
	 *
	 * @param customCompanyId the custom company ID of this expense
	 */
	public void setCustomCompanyId(long customCompanyId);

	/**
	 * Returns the type of this expense.
	 *
	 * @return the type of this expense
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this expense.
	 *
	 * @param type the type of this expense
	 */
	public void setType(String type);

	/**
	 * Returns the amount of this expense.
	 *
	 * @return the amount of this expense
	 */
	public double getAmount();

	/**
	 * Sets the amount of this expense.
	 *
	 * @param amount the amount of this expense
	 */
	public void setAmount(double amount);

	/**
	 * Returns the description of this expense.
	 *
	 * @return the description of this expense
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this expense.
	 *
	 * @param description the description of this expense
	 */
	public void setDescription(String description);

	/**
	 * Returns the expense date of this expense.
	 *
	 * @return the expense date of this expense
	 */
	public Date getExpenseDate();

	/**
	 * Sets the expense date of this expense.
	 *
	 * @param expenseDate the expense date of this expense
	 */
	public void setExpenseDate(Date expenseDate);

	/**
	 * Returns the create date of this expense.
	 *
	 * @return the create date of this expense
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this expense.
	 *
	 * @param createDate the create date of this expense
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this expense.
	 *
	 * @return the created by of this expense
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this expense.
	 *
	 * @param createdBy the created by of this expense
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this expense.
	 *
	 * @return the modified date of this expense
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this expense.
	 *
	 * @param modifiedDate the modified date of this expense
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this expense.
	 *
	 * @return the modified by of this expense
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this expense.
	 *
	 * @param modifiedBy the modified by of this expense
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Expense expense);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Expense> toCacheModel();

	@Override
	public Expense toEscapedModel();

	@Override
	public Expense toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}