/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Hording service. Represents a row in the &quot;SPHMS_Hording&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sphms.common.service.model.impl.HordingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sphms.common.service.model.impl.HordingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Hording
 * @see com.sphms.common.service.model.impl.HordingImpl
 * @see com.sphms.common.service.model.impl.HordingModelImpl
 * @generated
 */
@ProviderType
public interface HordingModel extends BaseModel<Hording> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hording model instance should use the {@link Hording} interface instead.
	 */

	/**
	 * Returns the primary key of this hording.
	 *
	 * @return the primary key of this hording
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this hording.
	 *
	 * @param primaryKey the primary key of this hording
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the hording ID of this hording.
	 *
	 * @return the hording ID of this hording
	 */
	public long getHordingId();

	/**
	 * Sets the hording ID of this hording.
	 *
	 * @param hordingId the hording ID of this hording
	 */
	public void setHordingId(long hordingId);

	/**
	 * Returns the title of this hording.
	 *
	 * @return the title of this hording
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this hording.
	 *
	 * @param title the title of this hording
	 */
	public void setTitle(String title);

	/**
	 * Returns the location of this hording.
	 *
	 * @return the location of this hording
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this hording.
	 *
	 * @param location the location of this hording
	 */
	public void setLocation(String location);

	/**
	 * Returns the city of this hording.
	 *
	 * @return the city of this hording
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this hording.
	 *
	 * @param city the city of this hording
	 */
	public void setCity(String city);

	/**
	 * Returns the district of this hording.
	 *
	 * @return the district of this hording
	 */
	@AutoEscape
	public String getDistrict();

	/**
	 * Sets the district of this hording.
	 *
	 * @param district the district of this hording
	 */
	public void setDistrict(String district);

	/**
	 * Returns the state of this hording.
	 *
	 * @return the state of this hording
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this hording.
	 *
	 * @param state the state of this hording
	 */
	public void setState(String state);

	/**
	 * Returns the hording type of this hording.
	 *
	 * @return the hording type of this hording
	 */
	@AutoEscape
	public String getHordingType();

	/**
	 * Sets the hording type of this hording.
	 *
	 * @param hordingType the hording type of this hording
	 */
	public void setHordingType(String hordingType);

	/**
	 * Returns the media vehicle of this hording.
	 *
	 * @return the media vehicle of this hording
	 */
	@AutoEscape
	public String getMediaVehicle();

	/**
	 * Sets the media vehicle of this hording.
	 *
	 * @param mediaVehicle the media vehicle of this hording
	 */
	public void setMediaVehicle(String mediaVehicle);

	/**
	 * Returns the size of this hording.
	 *
	 * @return the size of this hording
	 */
	@AutoEscape
	public String getSize();

	/**
	 * Sets the size of this hording.
	 *
	 * @param size the size of this hording
	 */
	public void setSize(String size);

	/**
	 * Returns the price per month of this hording.
	 *
	 * @return the price per month of this hording
	 */
	public double getPricePerMonth();

	/**
	 * Sets the price per month of this hording.
	 *
	 * @param pricePerMonth the price per month of this hording
	 */
	public void setPricePerMonth(double pricePerMonth);

	/**
	 * Returns the normal image ID of this hording.
	 *
	 * @return the normal image ID of this hording
	 */
	public long getNormalImageId();

	/**
	 * Sets the normal image ID of this hording.
	 *
	 * @param normalImageId the normal image ID of this hording
	 */
	public void setNormalImageId(long normalImageId);

	/**
	 * Returns the short image ID of this hording.
	 *
	 * @return the short image ID of this hording
	 */
	public long getShortImageId();

	/**
	 * Sets the short image ID of this hording.
	 *
	 * @param shortImageId the short image ID of this hording
	 */
	public void setShortImageId(long shortImageId);

	/**
	 * Returns the long image ID of this hording.
	 *
	 * @return the long image ID of this hording
	 */
	public long getLongImageId();

	/**
	 * Sets the long image ID of this hording.
	 *
	 * @param longImageId the long image ID of this hording
	 */
	public void setLongImageId(long longImageId);

	/**
	 * Returns the land lord ID of this hording.
	 *
	 * @return the land lord ID of this hording
	 */
	public long getLandLordId();

	/**
	 * Sets the land lord ID of this hording.
	 *
	 * @param landLordId the land lord ID of this hording
	 */
	public void setLandLordId(long landLordId);

	/**
	 * Returns the owner type of this hording.
	 *
	 * @return the owner type of this hording
	 */
	public int getOwnerType();

	/**
	 * Sets the owner type of this hording.
	 *
	 * @param ownerType the owner type of this hording
	 */
	public void setOwnerType(int ownerType);

	/**
	 * Returns the upin no of this hording.
	 *
	 * @return the upin no of this hording
	 */
	@AutoEscape
	public String getUpinNo();

	/**
	 * Sets the upin no of this hording.
	 *
	 * @param upinNo the upin no of this hording
	 */
	public void setUpinNo(String upinNo);

	/**
	 * Returns the mnc tax of this hording.
	 *
	 * @return the mnc tax of this hording
	 */
	public double getMncTax();

	/**
	 * Sets the mnc tax of this hording.
	 *
	 * @param mncTax the mnc tax of this hording
	 */
	public void setMncTax(double mncTax);

	/**
	 * Returns the other exp year of this hording.
	 *
	 * @return the other exp year of this hording
	 */
	public double getOtherExpYear();

	/**
	 * Sets the other exp year of this hording.
	 *
	 * @param otherExpYear the other exp year of this hording
	 */
	public void setOtherExpYear(double otherExpYear);

	/**
	 * Returns the status of this hording.
	 *
	 * @return the status of this hording
	 */
	public int getStatus();

	/**
	 * Sets the status of this hording.
	 *
	 * @param status the status of this hording
	 */
	public void setStatus(int status);

	/**
	 * Returns the create date of this hording.
	 *
	 * @return the create date of this hording
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this hording.
	 *
	 * @param createDate the create date of this hording
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this hording.
	 *
	 * @return the created by of this hording
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this hording.
	 *
	 * @param createdBy the created by of this hording
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this hording.
	 *
	 * @return the modified date of this hording
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this hording.
	 *
	 * @param modifiedDate the modified date of this hording
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this hording.
	 *
	 * @return the modified by of this hording
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this hording.
	 *
	 * @param modifiedBy the modified by of this hording
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Hording hording);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Hording> toCacheModel();

	@Override
	public Hording toEscapedModel();

	@Override
	public Hording toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}