/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LandLordPayment service. Represents a row in the &quot;SPHMS_LandLordPayment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sphms.common.service.model.impl.LandLordPaymentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sphms.common.service.model.impl.LandLordPaymentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LandLordPayment
 * @see com.sphms.common.service.model.impl.LandLordPaymentImpl
 * @see com.sphms.common.service.model.impl.LandLordPaymentModelImpl
 * @generated
 */
@ProviderType
public interface LandLordPaymentModel extends BaseModel<LandLordPayment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a land lord payment model instance should use the {@link LandLordPayment} interface instead.
	 */

	/**
	 * Returns the primary key of this land lord payment.
	 *
	 * @return the primary key of this land lord payment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this land lord payment.
	 *
	 * @param primaryKey the primary key of this land lord payment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the land lord payment ID of this land lord payment.
	 *
	 * @return the land lord payment ID of this land lord payment
	 */
	public long getLandLordPaymentId();

	/**
	 * Sets the land lord payment ID of this land lord payment.
	 *
	 * @param landLordPaymentId the land lord payment ID of this land lord payment
	 */
	public void setLandLordPaymentId(long landLordPaymentId);

	/**
	 * Returns the land load ID of this land lord payment.
	 *
	 * @return the land load ID of this land lord payment
	 */
	public long getLandLoadId();

	/**
	 * Sets the land load ID of this land lord payment.
	 *
	 * @param landLoadId the land load ID of this land lord payment
	 */
	public void setLandLoadId(long landLoadId);

	/**
	 * Returns the hording ID of this land lord payment.
	 *
	 * @return the hording ID of this land lord payment
	 */
	public long getHordingId();

	/**
	 * Sets the hording ID of this land lord payment.
	 *
	 * @param hordingId the hording ID of this land lord payment
	 */
	public void setHordingId(long hordingId);

	/**
	 * Returns the amount of this land lord payment.
	 *
	 * @return the amount of this land lord payment
	 */
	public double getAmount();

	/**
	 * Sets the amount of this land lord payment.
	 *
	 * @param amount the amount of this land lord payment
	 */
	public void setAmount(double amount);

	/**
	 * Returns the cheque no of this land lord payment.
	 *
	 * @return the cheque no of this land lord payment
	 */
	@AutoEscape
	public String getChequeNo();

	/**
	 * Sets the cheque no of this land lord payment.
	 *
	 * @param chequeNo the cheque no of this land lord payment
	 */
	public void setChequeNo(String chequeNo);

	/**
	 * Returns the bank name of this land lord payment.
	 *
	 * @return the bank name of this land lord payment
	 */
	@AutoEscape
	public String getBankName();

	/**
	 * Sets the bank name of this land lord payment.
	 *
	 * @param bankName the bank name of this land lord payment
	 */
	public void setBankName(String bankName);

	/**
	 * Returns the payment date of this land lord payment.
	 *
	 * @return the payment date of this land lord payment
	 */
	public Date getPaymentDate();

	/**
	 * Sets the payment date of this land lord payment.
	 *
	 * @param paymentDate the payment date of this land lord payment
	 */
	public void setPaymentDate(Date paymentDate);

	/**
	 * Returns the create date of this land lord payment.
	 *
	 * @return the create date of this land lord payment
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this land lord payment.
	 *
	 * @param createDate the create date of this land lord payment
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this land lord payment.
	 *
	 * @return the created by of this land lord payment
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this land lord payment.
	 *
	 * @param createdBy the created by of this land lord payment
	 */
	public void setCreatedBy(long createdBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LandLordPayment landLordPayment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LandLordPayment> toCacheModel();

	@Override
	public LandLordPayment toEscapedModel();

	@Override
	public LandLordPayment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}