/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the POPayment service. Represents a row in the &quot;SPHMS_POPayment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sphms.common.service.model.impl.POPaymentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sphms.common.service.model.impl.POPaymentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see POPayment
 * @see com.sphms.common.service.model.impl.POPaymentImpl
 * @see com.sphms.common.service.model.impl.POPaymentModelImpl
 * @generated
 */
@ProviderType
public interface POPaymentModel extends BaseModel<POPayment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a p o payment model instance should use the {@link POPayment} interface instead.
	 */

	/**
	 * Returns the primary key of this p o payment.
	 *
	 * @return the primary key of this p o payment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this p o payment.
	 *
	 * @param primaryKey the primary key of this p o payment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the po payment ID of this p o payment.
	 *
	 * @return the po payment ID of this p o payment
	 */
	public long getPoPaymentId();

	/**
	 * Sets the po payment ID of this p o payment.
	 *
	 * @param poPaymentId the po payment ID of this p o payment
	 */
	public void setPoPaymentId(long poPaymentId);

	/**
	 * Returns the billing ID of this p o payment.
	 *
	 * @return the billing ID of this p o payment
	 */
	public long getBillingId();

	/**
	 * Sets the billing ID of this p o payment.
	 *
	 * @param billingId the billing ID of this p o payment
	 */
	public void setBillingId(long billingId);

	/**
	 * Returns the land lord ID of this p o payment.
	 *
	 * @return the land lord ID of this p o payment
	 */
	public long getLandLordId();

	/**
	 * Sets the land lord ID of this p o payment.
	 *
	 * @param landLordId the land lord ID of this p o payment
	 */
	public void setLandLordId(long landLordId);

	/**
	 * Returns the amount of this p o payment.
	 *
	 * @return the amount of this p o payment
	 */
	public double getAmount();

	/**
	 * Sets the amount of this p o payment.
	 *
	 * @param amount the amount of this p o payment
	 */
	public void setAmount(double amount);

	/**
	 * Returns the gst of this p o payment.
	 *
	 * @return the gst of this p o payment
	 */
	public double getGst();

	/**
	 * Sets the gst of this p o payment.
	 *
	 * @param gst the gst of this p o payment
	 */
	public void setGst(double gst);

	/**
	 * Returns the cheque no of this p o payment.
	 *
	 * @return the cheque no of this p o payment
	 */
	@AutoEscape
	public String getChequeNo();

	/**
	 * Sets the cheque no of this p o payment.
	 *
	 * @param chequeNo the cheque no of this p o payment
	 */
	public void setChequeNo(String chequeNo);

	/**
	 * Returns the payment date of this p o payment.
	 *
	 * @return the payment date of this p o payment
	 */
	public Date getPaymentDate();

	/**
	 * Sets the payment date of this p o payment.
	 *
	 * @param paymentDate the payment date of this p o payment
	 */
	public void setPaymentDate(Date paymentDate);

	/**
	 * Returns the create date of this p o payment.
	 *
	 * @return the create date of this p o payment
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this p o payment.
	 *
	 * @param createDate the create date of this p o payment
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this p o payment.
	 *
	 * @return the created by of this p o payment
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this p o payment.
	 *
	 * @param createdBy the created by of this p o payment
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this p o payment.
	 *
	 * @return the modified date of this p o payment
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this p o payment.
	 *
	 * @param modifiedDate the modified date of this p o payment
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this p o payment.
	 *
	 * @return the modified by of this p o payment
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this p o payment.
	 *
	 * @param modifiedBy the modified by of this p o payment
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(POPayment poPayment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<POPayment> toCacheModel();

	@Override
	public POPayment toEscapedModel();

	@Override
	public POPayment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}