/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SupplierBill service. Represents a row in the &quot;SPHMS_SupplierBill&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sphms.common.service.model.impl.SupplierBillModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sphms.common.service.model.impl.SupplierBillImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupplierBill
 * @see com.sphms.common.service.model.impl.SupplierBillImpl
 * @see com.sphms.common.service.model.impl.SupplierBillModelImpl
 * @generated
 */
@ProviderType
public interface SupplierBillModel extends BaseModel<SupplierBill>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a supplier bill model instance should use the {@link SupplierBill} interface instead.
	 */

	/**
	 * Returns the primary key of this supplier bill.
	 *
	 * @return the primary key of this supplier bill
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this supplier bill.
	 *
	 * @param primaryKey the primary key of this supplier bill
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the supplier bill ID of this supplier bill.
	 *
	 * @return the supplier bill ID of this supplier bill
	 */
	public long getSupplierBillId();

	/**
	 * Sets the supplier bill ID of this supplier bill.
	 *
	 * @param supplierBillId the supplier bill ID of this supplier bill
	 */
	public void setSupplierBillId(long supplierBillId);

	/**
	 * Returns the supplier ID of this supplier bill.
	 *
	 * @return the supplier ID of this supplier bill
	 */
	public long getSupplierId();

	/**
	 * Sets the supplier ID of this supplier bill.
	 *
	 * @param supplierId the supplier ID of this supplier bill
	 */
	public void setSupplierId(long supplierId);

	/**
	 * Returns the company ID of this supplier bill.
	 *
	 * @return the company ID of this supplier bill
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this supplier bill.
	 *
	 * @param companyId the company ID of this supplier bill
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the supplier bill no of this supplier bill.
	 *
	 * @return the supplier bill no of this supplier bill
	 */
	@AutoEscape
	public String getSupplierBillNo();

	/**
	 * Sets the supplier bill no of this supplier bill.
	 *
	 * @param supplierBillNo the supplier bill no of this supplier bill
	 */
	public void setSupplierBillNo(String supplierBillNo);

	/**
	 * Returns the supplier bill desc of this supplier bill.
	 *
	 * @return the supplier bill desc of this supplier bill
	 */
	@AutoEscape
	public String getSupplierBillDesc();

	/**
	 * Sets the supplier bill desc of this supplier bill.
	 *
	 * @param supplierBillDesc the supplier bill desc of this supplier bill
	 */
	public void setSupplierBillDesc(String supplierBillDesc);

	/**
	 * Returns the supplier bill type of this supplier bill.
	 *
	 * @return the supplier bill type of this supplier bill
	 */
	@AutoEscape
	public String getSupplierBillType();

	/**
	 * Sets the supplier bill type of this supplier bill.
	 *
	 * @param supplierBillType the supplier bill type of this supplier bill
	 */
	public void setSupplierBillType(String supplierBillType);

	/**
	 * Returns the supplier bill date of this supplier bill.
	 *
	 * @return the supplier bill date of this supplier bill
	 */
	public Date getSupplierBillDate();

	/**
	 * Sets the supplier bill date of this supplier bill.
	 *
	 * @param supplierBillDate the supplier bill date of this supplier bill
	 */
	public void setSupplierBillDate(Date supplierBillDate);

	/**
	 * Returns the amount of this supplier bill.
	 *
	 * @return the amount of this supplier bill
	 */
	public double getAmount();

	/**
	 * Sets the amount of this supplier bill.
	 *
	 * @param amount the amount of this supplier bill
	 */
	public void setAmount(double amount);

	/**
	 * Returns the gst of this supplier bill.
	 *
	 * @return the gst of this supplier bill
	 */
	public double getGst();

	/**
	 * Sets the gst of this supplier bill.
	 *
	 * @param gst the gst of this supplier bill
	 */
	public void setGst(double gst);

	/**
	 * Returns the create date of this supplier bill.
	 *
	 * @return the create date of this supplier bill
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this supplier bill.
	 *
	 * @param createDate the create date of this supplier bill
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this supplier bill.
	 *
	 * @return the created by of this supplier bill
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this supplier bill.
	 *
	 * @param createdBy the created by of this supplier bill
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this supplier bill.
	 *
	 * @return the modified date of this supplier bill
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this supplier bill.
	 *
	 * @param modifiedDate the modified date of this supplier bill
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this supplier bill.
	 *
	 * @return the modified by of this supplier bill
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this supplier bill.
	 *
	 * @param modifiedBy the modified by of this supplier bill
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SupplierBill supplierBill);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SupplierBill> toCacheModel();

	@Override
	public SupplierBill toEscapedModel();

	@Override
	public SupplierBill toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}