/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Supplier service. Represents a row in the &quot;SPHMS_Supplier&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sphms.common.service.model.impl.SupplierModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sphms.common.service.model.impl.SupplierImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Supplier
 * @see com.sphms.common.service.model.impl.SupplierImpl
 * @see com.sphms.common.service.model.impl.SupplierModelImpl
 * @generated
 */
@ProviderType
public interface SupplierModel extends BaseModel<Supplier> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a supplier model instance should use the {@link Supplier} interface instead.
	 */

	/**
	 * Returns the primary key of this supplier.
	 *
	 * @return the primary key of this supplier
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this supplier.
	 *
	 * @param primaryKey the primary key of this supplier
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the supplier ID of this supplier.
	 *
	 * @return the supplier ID of this supplier
	 */
	public long getSupplierId();

	/**
	 * Sets the supplier ID of this supplier.
	 *
	 * @param supplierId the supplier ID of this supplier
	 */
	public void setSupplierId(long supplierId);

	/**
	 * Returns the supplier name of this supplier.
	 *
	 * @return the supplier name of this supplier
	 */
	@AutoEscape
	public String getSupplierName();

	/**
	 * Sets the supplier name of this supplier.
	 *
	 * @param supplierName the supplier name of this supplier
	 */
	public void setSupplierName(String supplierName);

	/**
	 * Returns the address1 of this supplier.
	 *
	 * @return the address1 of this supplier
	 */
	@AutoEscape
	public String getAddress1();

	/**
	 * Sets the address1 of this supplier.
	 *
	 * @param address1 the address1 of this supplier
	 */
	public void setAddress1(String address1);

	/**
	 * Returns the address2 of this supplier.
	 *
	 * @return the address2 of this supplier
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this supplier.
	 *
	 * @param address2 the address2 of this supplier
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this supplier.
	 *
	 * @return the city of this supplier
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this supplier.
	 *
	 * @param city the city of this supplier
	 */
	public void setCity(String city);

	/**
	 * Returns the pan no of this supplier.
	 *
	 * @return the pan no of this supplier
	 */
	@AutoEscape
	public String getPanNo();

	/**
	 * Sets the pan no of this supplier.
	 *
	 * @param panNo the pan no of this supplier
	 */
	public void setPanNo(String panNo);

	/**
	 * Returns the gst no of this supplier.
	 *
	 * @return the gst no of this supplier
	 */
	@AutoEscape
	public String getGstNo();

	/**
	 * Sets the gst no of this supplier.
	 *
	 * @param gstNo the gst no of this supplier
	 */
	public void setGstNo(String gstNo);

	/**
	 * Returns the state of this supplier.
	 *
	 * @return the state of this supplier
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this supplier.
	 *
	 * @param state the state of this supplier
	 */
	public void setState(String state);

	/**
	 * Returns the status of this supplier.
	 *
	 * @return the status of this supplier
	 */
	public int getStatus();

	/**
	 * Sets the status of this supplier.
	 *
	 * @param status the status of this supplier
	 */
	public void setStatus(int status);

	/**
	 * Returns the contact person name of this supplier.
	 *
	 * @return the contact person name of this supplier
	 */
	@AutoEscape
	public String getContactPersonName();

	/**
	 * Sets the contact person name of this supplier.
	 *
	 * @param contactPersonName the contact person name of this supplier
	 */
	public void setContactPersonName(String contactPersonName);

	/**
	 * Returns the contact person email of this supplier.
	 *
	 * @return the contact person email of this supplier
	 */
	@AutoEscape
	public String getContactPersonEmail();

	/**
	 * Sets the contact person email of this supplier.
	 *
	 * @param contactPersonEmail the contact person email of this supplier
	 */
	public void setContactPersonEmail(String contactPersonEmail);

	/**
	 * Returns the contact person phone no of this supplier.
	 *
	 * @return the contact person phone no of this supplier
	 */
	@AutoEscape
	public String getContactPersonPhoneNo();

	/**
	 * Sets the contact person phone no of this supplier.
	 *
	 * @param contactPersonPhoneNo the contact person phone no of this supplier
	 */
	public void setContactPersonPhoneNo(String contactPersonPhoneNo);

	/**
	 * Returns the create date of this supplier.
	 *
	 * @return the create date of this supplier
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this supplier.
	 *
	 * @param createDate the create date of this supplier
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this supplier.
	 *
	 * @return the created by of this supplier
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this supplier.
	 *
	 * @param createdBy the created by of this supplier
	 */
	public void setCreatedBy(long createdBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Supplier supplier);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Supplier> toCacheModel();

	@Override
	public Supplier toEscapedModel();

	@Override
	public Supplier toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}