/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SupplierBillPayment service. Represents a row in the &quot;SPHMS_SupplierBillPayment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sphms.common.service.model.impl.SupplierBillPaymentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sphms.common.service.model.impl.SupplierBillPaymentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupplierBillPayment
 * @see com.sphms.common.service.model.impl.SupplierBillPaymentImpl
 * @see com.sphms.common.service.model.impl.SupplierBillPaymentModelImpl
 * @generated
 */
@ProviderType
public interface SupplierBillPaymentModel extends BaseModel<SupplierBillPayment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a supplier bill payment model instance should use the {@link SupplierBillPayment} interface instead.
	 */

	/**
	 * Returns the primary key of this supplier bill payment.
	 *
	 * @return the primary key of this supplier bill payment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this supplier bill payment.
	 *
	 * @param primaryKey the primary key of this supplier bill payment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the supplier bill payment ID of this supplier bill payment.
	 *
	 * @return the supplier bill payment ID of this supplier bill payment
	 */
	public long getSupplierBillPaymentId();

	/**
	 * Sets the supplier bill payment ID of this supplier bill payment.
	 *
	 * @param supplierBillPaymentId the supplier bill payment ID of this supplier bill payment
	 */
	public void setSupplierBillPaymentId(long supplierBillPaymentId);

	/**
	 * Returns the supplier bill ID of this supplier bill payment.
	 *
	 * @return the supplier bill ID of this supplier bill payment
	 */
	public long getSupplierBillId();

	/**
	 * Sets the supplier bill ID of this supplier bill payment.
	 *
	 * @param supplierBillId the supplier bill ID of this supplier bill payment
	 */
	public void setSupplierBillId(long supplierBillId);

	/**
	 * Returns the supplier ID of this supplier bill payment.
	 *
	 * @return the supplier ID of this supplier bill payment
	 */
	public long getSupplierId();

	/**
	 * Sets the supplier ID of this supplier bill payment.
	 *
	 * @param supplierId the supplier ID of this supplier bill payment
	 */
	public void setSupplierId(long supplierId);

	/**
	 * Returns the amount of this supplier bill payment.
	 *
	 * @return the amount of this supplier bill payment
	 */
	public double getAmount();

	/**
	 * Sets the amount of this supplier bill payment.
	 *
	 * @param amount the amount of this supplier bill payment
	 */
	public void setAmount(double amount);

	/**
	 * Returns the gst of this supplier bill payment.
	 *
	 * @return the gst of this supplier bill payment
	 */
	public double getGst();

	/**
	 * Sets the gst of this supplier bill payment.
	 *
	 * @param gst the gst of this supplier bill payment
	 */
	public void setGst(double gst);

	/**
	 * Returns the cheque no of this supplier bill payment.
	 *
	 * @return the cheque no of this supplier bill payment
	 */
	@AutoEscape
	public String getChequeNo();

	/**
	 * Sets the cheque no of this supplier bill payment.
	 *
	 * @param chequeNo the cheque no of this supplier bill payment
	 */
	public void setChequeNo(String chequeNo);

	/**
	 * Returns the payment date of this supplier bill payment.
	 *
	 * @return the payment date of this supplier bill payment
	 */
	public Date getPaymentDate();

	/**
	 * Sets the payment date of this supplier bill payment.
	 *
	 * @param paymentDate the payment date of this supplier bill payment
	 */
	public void setPaymentDate(Date paymentDate);

	/**
	 * Returns the create date of this supplier bill payment.
	 *
	 * @return the create date of this supplier bill payment
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this supplier bill payment.
	 *
	 * @param createDate the create date of this supplier bill payment
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this supplier bill payment.
	 *
	 * @return the created by of this supplier bill payment
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this supplier bill payment.
	 *
	 * @param createdBy the created by of this supplier bill payment
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this supplier bill payment.
	 *
	 * @return the modified date of this supplier bill payment
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this supplier bill payment.
	 *
	 * @param modifiedDate the modified date of this supplier bill payment
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this supplier bill payment.
	 *
	 * @return the modified by of this supplier bill payment
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this supplier bill payment.
	 *
	 * @param modifiedBy the modified by of this supplier bill payment
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SupplierBillPayment supplierBillPayment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SupplierBillPayment> toCacheModel();

	@Override
	public SupplierBillPayment toEscapedModel();

	@Override
	public SupplierBillPayment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}