/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.sphms.common.service.model.Billing_Hording;
import com.sphms.common.service.service.Billing_HordingLocalServiceUtil;

/**
 * The extended model base implementation for the Billing_Hording service. Represents a row in the &quot;SPHMS_Billing_Hording&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Billing_HordingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Billing_HordingImpl
 * @see Billing_Hording
 * @generated
 */
@ProviderType
public abstract class Billing_HordingBaseImpl extends Billing_HordingModelImpl
	implements Billing_Hording {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a billing_ hording model instance should use the {@link Billing_Hording} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Billing_HordingLocalServiceUtil.addBilling_Hording(this);
		}
		else {
			Billing_HordingLocalServiceUtil.updateBilling_Hording(this);
		}
	}
}