/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.sphms.common.service.model.Booking;
import com.sphms.common.service.model.BookingModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Booking service. Represents a row in the &quot;SPHMS_Booking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link BookingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BookingImpl
 * @see Booking
 * @see BookingModel
 * @generated
 */
@ProviderType
public class BookingModelImpl extends BaseModelImpl<Booking>
	implements BookingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a booking model instance should use the {@link Booking} interface instead.
	 */
	public static final String TABLE_NAME = "SPHMS_Booking";
	public static final Object[][] TABLE_COLUMNS = {
			{ "bookingId", Types.BIGINT },
			{ "customCompanyId", Types.BIGINT },
			{ "campaignTitle", Types.VARCHAR },
			{ "client", Types.BIGINT },
			{ "billId", Types.BIGINT },
			{ "startDate", Types.TIMESTAMP },
			{ "endDate", Types.TIMESTAMP },
			{ "createDate", Types.TIMESTAMP },
			{ "createdBy", Types.BIGINT },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "modifiedBy", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("bookingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("customCompanyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("campaignTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("client", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("billId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table SPHMS_Booking (bookingId LONG not null primary key,customCompanyId LONG,campaignTitle VARCHAR(100) null,client LONG,billId LONG,startDate DATE null,endDate DATE null,createDate DATE null,createdBy LONG,modifiedDate DATE null,modifiedBy LONG)";
	public static final String TABLE_SQL_DROP = "drop table SPHMS_Booking";
	public static final String ORDER_BY_JPQL = " ORDER BY booking.bookingId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPHMS_Booking.bookingId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.sphms.common.service.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.sphms.common.service.model.Booking"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.sphms.common.service.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.sphms.common.service.model.Booking"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.sphms.common.service.service.util.PropsUtil.get(
				"lock.expiration.time.com.sphms.common.service.model.Booking"));

	public BookingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _bookingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBookingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _bookingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Booking.class;
	}

	@Override
	public String getModelClassName() {
		return Booking.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("bookingId", getBookingId());
		attributes.put("customCompanyId", getCustomCompanyId());
		attributes.put("campaignTitle", getCampaignTitle());
		attributes.put("client", getClient());
		attributes.put("billId", getBillId());
		attributes.put("startDate", getStartDate());
		attributes.put("endDate", getEndDate());
		attributes.put("createDate", getCreateDate());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("modifiedBy", getModifiedBy());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long bookingId = (Long)attributes.get("bookingId");

		if (bookingId != null) {
			setBookingId(bookingId);
		}

		Long customCompanyId = (Long)attributes.get("customCompanyId");

		if (customCompanyId != null) {
			setCustomCompanyId(customCompanyId);
		}

		String campaignTitle = (String)attributes.get("campaignTitle");

		if (campaignTitle != null) {
			setCampaignTitle(campaignTitle);
		}

		Long client = (Long)attributes.get("client");

		if (client != null) {
			setClient(client);
		}

		Long billId = (Long)attributes.get("billId");

		if (billId != null) {
			setBillId(billId);
		}

		Date startDate = (Date)attributes.get("startDate");

		if (startDate != null) {
			setStartDate(startDate);
		}

		Date endDate = (Date)attributes.get("endDate");

		if (endDate != null) {
			setEndDate(endDate);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long createdBy = (Long)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long modifiedBy = (Long)attributes.get("modifiedBy");

		if (modifiedBy != null) {
			setModifiedBy(modifiedBy);
		}
	}

	@Override
	public long getBookingId() {
		return _bookingId;
	}

	@Override
	public void setBookingId(long bookingId) {
		_bookingId = bookingId;
	}

	@Override
	public long getCustomCompanyId() {
		return _customCompanyId;
	}

	@Override
	public void setCustomCompanyId(long customCompanyId) {
		_customCompanyId = customCompanyId;
	}

	@Override
	public String getCampaignTitle() {
		if (_campaignTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _campaignTitle;
		}
	}

	@Override
	public void setCampaignTitle(String campaignTitle) {
		_campaignTitle = campaignTitle;
	}

	@Override
	public long getClient() {
		return _client;
	}

	@Override
	public void setClient(long client) {
		_client = client;
	}

	@Override
	public long getBillId() {
		return _billId;
	}

	@Override
	public void setBillId(long billId) {
		_billId = billId;
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_endDate = endDate;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		_createdBy = createdBy;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Booking.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Booking toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Booking)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BookingImpl bookingImpl = new BookingImpl();

		bookingImpl.setBookingId(getBookingId());
		bookingImpl.setCustomCompanyId(getCustomCompanyId());
		bookingImpl.setCampaignTitle(getCampaignTitle());
		bookingImpl.setClient(getClient());
		bookingImpl.setBillId(getBillId());
		bookingImpl.setStartDate(getStartDate());
		bookingImpl.setEndDate(getEndDate());
		bookingImpl.setCreateDate(getCreateDate());
		bookingImpl.setCreatedBy(getCreatedBy());
		bookingImpl.setModifiedDate(getModifiedDate());
		bookingImpl.setModifiedBy(getModifiedBy());

		bookingImpl.resetOriginalValues();

		return bookingImpl;
	}

	@Override
	public int compareTo(Booking booking) {
		long primaryKey = booking.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Booking)) {
			return false;
		}

		Booking booking = (Booking)obj;

		long primaryKey = booking.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		BookingModelImpl bookingModelImpl = this;

		bookingModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<Booking> toCacheModel() {
		BookingCacheModel bookingCacheModel = new BookingCacheModel();

		bookingCacheModel.bookingId = getBookingId();

		bookingCacheModel.customCompanyId = getCustomCompanyId();

		bookingCacheModel.campaignTitle = getCampaignTitle();

		String campaignTitle = bookingCacheModel.campaignTitle;

		if ((campaignTitle != null) && (campaignTitle.length() == 0)) {
			bookingCacheModel.campaignTitle = null;
		}

		bookingCacheModel.client = getClient();

		bookingCacheModel.billId = getBillId();

		Date startDate = getStartDate();

		if (startDate != null) {
			bookingCacheModel.startDate = startDate.getTime();
		}
		else {
			bookingCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			bookingCacheModel.endDate = endDate.getTime();
		}
		else {
			bookingCacheModel.endDate = Long.MIN_VALUE;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			bookingCacheModel.createDate = createDate.getTime();
		}
		else {
			bookingCacheModel.createDate = Long.MIN_VALUE;
		}

		bookingCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			bookingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			bookingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		bookingCacheModel.modifiedBy = getModifiedBy();

		return bookingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{bookingId=");
		sb.append(getBookingId());
		sb.append(", customCompanyId=");
		sb.append(getCustomCompanyId());
		sb.append(", campaignTitle=");
		sb.append(getCampaignTitle());
		sb.append(", client=");
		sb.append(getClient());
		sb.append(", billId=");
		sb.append(getBillId());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", endDate=");
		sb.append(getEndDate());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", modifiedBy=");
		sb.append(getModifiedBy());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.sphms.common.service.model.Booking");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>bookingId</column-name><column-value><![CDATA[");
		sb.append(getBookingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customCompanyId</column-name><column-value><![CDATA[");
		sb.append(getCustomCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>campaignTitle</column-name><column-value><![CDATA[");
		sb.append(getCampaignTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>client</column-name><column-value><![CDATA[");
		sb.append(getClient());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>billId</column-name><column-value><![CDATA[");
		sb.append(getBillId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDate</column-name><column-value><![CDATA[");
		sb.append(getEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Booking.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Booking.class
		};
	private long _bookingId;
	private long _customCompanyId;
	private String _campaignTitle;
	private long _client;
	private long _billId;
	private Date _startDate;
	private Date _endDate;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private Booking _escapedModel;
}