/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.sphms.common.service.model.POPayment;
import com.sphms.common.service.service.POPaymentLocalServiceUtil;

/**
 * The extended model base implementation for the POPayment service. Represents a row in the &quot;SPHMS_POPayment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link POPaymentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see POPaymentImpl
 * @see POPayment
 * @generated
 */
@ProviderType
public abstract class POPaymentBaseImpl extends POPaymentModelImpl
	implements POPayment {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a p o payment model instance should use the {@link POPayment} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			POPaymentLocalServiceUtil.addPOPayment(this);
		}
		else {
			POPaymentLocalServiceUtil.updatePOPayment(this);
		}
	}
}