/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.sphms.common.service.model.Proposal_Hording;
import com.sphms.common.service.model.Proposal_HordingModel;
import com.sphms.common.service.service.persistence.Proposal_HordingPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Proposal_Hording service. Represents a row in the &quot;SPHMS_Proposal_Hording&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link Proposal_HordingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Proposal_HordingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Proposal_HordingImpl
 * @see Proposal_Hording
 * @see Proposal_HordingModel
 * @generated
 */
@ProviderType
public class Proposal_HordingModelImpl extends BaseModelImpl<Proposal_Hording>
	implements Proposal_HordingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a proposal_ hording model instance should use the {@link Proposal_Hording} interface instead.
	 */
	public static final String TABLE_NAME = "SPHMS_Proposal_Hording";
	public static final Object[][] TABLE_COLUMNS = {
			{ "proposalId", Types.BIGINT },
			{ "hordingId", Types.BIGINT },
			{ "mountingCharge", Types.DOUBLE },
			{ "printingCharge", Types.DOUBLE },
			{ "units", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("proposalId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("hordingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("mountingCharge", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("printingCharge", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("units", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table SPHMS_Proposal_Hording (proposalId LONG not null,hordingId LONG not null,mountingCharge DOUBLE,printingCharge DOUBLE,units INTEGER,primary key (proposalId, hordingId))";
	public static final String TABLE_SQL_DROP = "drop table SPHMS_Proposal_Hording";
	public static final String ORDER_BY_JPQL = " ORDER BY proposal_Hording.id.proposalId ASC, proposal_Hording.id.hordingId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPHMS_Proposal_Hording.proposalId ASC, SPHMS_Proposal_Hording.hordingId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.sphms.common.service.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.sphms.common.service.model.Proposal_Hording"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.sphms.common.service.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.sphms.common.service.model.Proposal_Hording"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.sphms.common.service.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.sphms.common.service.model.Proposal_Hording"),
			true);
	public static final long PROPOSALID_COLUMN_BITMASK = 1L;
	public static final long HORDINGID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.sphms.common.service.service.util.PropsUtil.get(
				"lock.expiration.time.com.sphms.common.service.model.Proposal_Hording"));

	public Proposal_HordingModelImpl() {
	}

	@Override
	public Proposal_HordingPK getPrimaryKey() {
		return new Proposal_HordingPK(_proposalId, _hordingId);
	}

	@Override
	public void setPrimaryKey(Proposal_HordingPK primaryKey) {
		setProposalId(primaryKey.proposalId);
		setHordingId(primaryKey.hordingId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new Proposal_HordingPK(_proposalId, _hordingId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((Proposal_HordingPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Proposal_Hording.class;
	}

	@Override
	public String getModelClassName() {
		return Proposal_Hording.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("proposalId", getProposalId());
		attributes.put("hordingId", getHordingId());
		attributes.put("mountingCharge", getMountingCharge());
		attributes.put("printingCharge", getPrintingCharge());
		attributes.put("units", getUnits());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long proposalId = (Long)attributes.get("proposalId");

		if (proposalId != null) {
			setProposalId(proposalId);
		}

		Long hordingId = (Long)attributes.get("hordingId");

		if (hordingId != null) {
			setHordingId(hordingId);
		}

		Double mountingCharge = (Double)attributes.get("mountingCharge");

		if (mountingCharge != null) {
			setMountingCharge(mountingCharge);
		}

		Double printingCharge = (Double)attributes.get("printingCharge");

		if (printingCharge != null) {
			setPrintingCharge(printingCharge);
		}

		Integer units = (Integer)attributes.get("units");

		if (units != null) {
			setUnits(units);
		}
	}

	@Override
	public long getProposalId() {
		return _proposalId;
	}

	@Override
	public void setProposalId(long proposalId) {
		_columnBitmask |= PROPOSALID_COLUMN_BITMASK;

		if (!_setOriginalProposalId) {
			_setOriginalProposalId = true;

			_originalProposalId = _proposalId;
		}

		_proposalId = proposalId;
	}

	public long getOriginalProposalId() {
		return _originalProposalId;
	}

	@Override
	public long getHordingId() {
		return _hordingId;
	}

	@Override
	public void setHordingId(long hordingId) {
		_hordingId = hordingId;
	}

	@Override
	public double getMountingCharge() {
		return _mountingCharge;
	}

	@Override
	public void setMountingCharge(double mountingCharge) {
		_mountingCharge = mountingCharge;
	}

	@Override
	public double getPrintingCharge() {
		return _printingCharge;
	}

	@Override
	public void setPrintingCharge(double printingCharge) {
		_printingCharge = printingCharge;
	}

	@Override
	public int getUnits() {
		return _units;
	}

	@Override
	public void setUnits(int units) {
		_units = units;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Proposal_Hording toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Proposal_Hording)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Proposal_HordingImpl proposal_HordingImpl = new Proposal_HordingImpl();

		proposal_HordingImpl.setProposalId(getProposalId());
		proposal_HordingImpl.setHordingId(getHordingId());
		proposal_HordingImpl.setMountingCharge(getMountingCharge());
		proposal_HordingImpl.setPrintingCharge(getPrintingCharge());
		proposal_HordingImpl.setUnits(getUnits());

		proposal_HordingImpl.resetOriginalValues();

		return proposal_HordingImpl;
	}

	@Override
	public int compareTo(Proposal_Hording proposal_Hording) {
		Proposal_HordingPK primaryKey = proposal_Hording.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Proposal_Hording)) {
			return false;
		}

		Proposal_Hording proposal_Hording = (Proposal_Hording)obj;

		Proposal_HordingPK primaryKey = proposal_Hording.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		Proposal_HordingModelImpl proposal_HordingModelImpl = this;

		proposal_HordingModelImpl._originalProposalId = proposal_HordingModelImpl._proposalId;

		proposal_HordingModelImpl._setOriginalProposalId = false;

		proposal_HordingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Proposal_Hording> toCacheModel() {
		Proposal_HordingCacheModel proposal_HordingCacheModel = new Proposal_HordingCacheModel();

		proposal_HordingCacheModel.proposal_HordingPK = getPrimaryKey();

		proposal_HordingCacheModel.proposalId = getProposalId();

		proposal_HordingCacheModel.hordingId = getHordingId();

		proposal_HordingCacheModel.mountingCharge = getMountingCharge();

		proposal_HordingCacheModel.printingCharge = getPrintingCharge();

		proposal_HordingCacheModel.units = getUnits();

		return proposal_HordingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{proposalId=");
		sb.append(getProposalId());
		sb.append(", hordingId=");
		sb.append(getHordingId());
		sb.append(", mountingCharge=");
		sb.append(getMountingCharge());
		sb.append(", printingCharge=");
		sb.append(getPrintingCharge());
		sb.append(", units=");
		sb.append(getUnits());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.sphms.common.service.model.Proposal_Hording");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>proposalId</column-name><column-value><![CDATA[");
		sb.append(getProposalId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hordingId</column-name><column-value><![CDATA[");
		sb.append(getHordingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mountingCharge</column-name><column-value><![CDATA[");
		sb.append(getMountingCharge());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>printingCharge</column-name><column-value><![CDATA[");
		sb.append(getPrintingCharge());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>units</column-name><column-value><![CDATA[");
		sb.append(getUnits());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Proposal_Hording.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Proposal_Hording.class
		};
	private long _proposalId;
	private long _originalProposalId;
	private boolean _setOriginalProposalId;
	private long _hordingId;
	private double _mountingCharge;
	private double _printingCharge;
	private int _units;
	private long _columnBitmask;
	private Proposal_Hording _escapedModel;
}