/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sphms.common.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.sphms.common.service.model.SupplierBill;
import com.sphms.common.service.model.SupplierBillModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the SupplierBill service. Represents a row in the &quot;SPHMS_SupplierBill&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link SupplierBillModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SupplierBillImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupplierBillImpl
 * @see SupplierBill
 * @see SupplierBillModel
 * @generated
 */
@ProviderType
public class SupplierBillModelImpl extends BaseModelImpl<SupplierBill>
	implements SupplierBillModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a supplier bill model instance should use the {@link SupplierBill} interface instead.
	 */
	public static final String TABLE_NAME = "SPHMS_SupplierBill";
	public static final Object[][] TABLE_COLUMNS = {
			{ "supplierBillId", Types.BIGINT },
			{ "supplierId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "supplierBillNo", Types.VARCHAR },
			{ "supplierBillDesc", Types.VARCHAR },
			{ "supplierBillType", Types.VARCHAR },
			{ "supplierBillDate", Types.TIMESTAMP },
			{ "amount", Types.DOUBLE },
			{ "gst", Types.DOUBLE },
			{ "createDate", Types.TIMESTAMP },
			{ "createdBy", Types.BIGINT },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "modifiedBy", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("supplierBillId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("supplierId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("supplierBillNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("supplierBillDesc", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("supplierBillType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("supplierBillDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("amount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("gst", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table SPHMS_SupplierBill (supplierBillId LONG not null primary key,supplierId LONG,companyId LONG,supplierBillNo VARCHAR(75) null,supplierBillDesc VARCHAR(75) null,supplierBillType VARCHAR(75) null,supplierBillDate DATE null,amount DOUBLE,gst DOUBLE,createDate DATE null,createdBy LONG,modifiedDate DATE null,modifiedBy LONG)";
	public static final String TABLE_SQL_DROP = "drop table SPHMS_SupplierBill";
	public static final String ORDER_BY_JPQL = " ORDER BY supplierBill.supplierBillId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPHMS_SupplierBill.supplierBillId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.sphms.common.service.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.sphms.common.service.model.SupplierBill"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.sphms.common.service.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.sphms.common.service.model.SupplierBill"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.sphms.common.service.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.sphms.common.service.model.SupplierBill"),
			true);
	public static final long SUPPLIERID_COLUMN_BITMASK = 1L;
	public static final long SUPPLIERBILLID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.sphms.common.service.service.util.PropsUtil.get(
				"lock.expiration.time.com.sphms.common.service.model.SupplierBill"));

	public SupplierBillModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _supplierBillId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSupplierBillId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _supplierBillId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SupplierBill.class;
	}

	@Override
	public String getModelClassName() {
		return SupplierBill.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("supplierBillId", getSupplierBillId());
		attributes.put("supplierId", getSupplierId());
		attributes.put("companyId", getCompanyId());
		attributes.put("supplierBillNo", getSupplierBillNo());
		attributes.put("supplierBillDesc", getSupplierBillDesc());
		attributes.put("supplierBillType", getSupplierBillType());
		attributes.put("supplierBillDate", getSupplierBillDate());
		attributes.put("amount", getAmount());
		attributes.put("gst", getGst());
		attributes.put("createDate", getCreateDate());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("modifiedBy", getModifiedBy());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long supplierBillId = (Long)attributes.get("supplierBillId");

		if (supplierBillId != null) {
			setSupplierBillId(supplierBillId);
		}

		Long supplierId = (Long)attributes.get("supplierId");

		if (supplierId != null) {
			setSupplierId(supplierId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		String supplierBillNo = (String)attributes.get("supplierBillNo");

		if (supplierBillNo != null) {
			setSupplierBillNo(supplierBillNo);
		}

		String supplierBillDesc = (String)attributes.get("supplierBillDesc");

		if (supplierBillDesc != null) {
			setSupplierBillDesc(supplierBillDesc);
		}

		String supplierBillType = (String)attributes.get("supplierBillType");

		if (supplierBillType != null) {
			setSupplierBillType(supplierBillType);
		}

		Date supplierBillDate = (Date)attributes.get("supplierBillDate");

		if (supplierBillDate != null) {
			setSupplierBillDate(supplierBillDate);
		}

		Double amount = (Double)attributes.get("amount");

		if (amount != null) {
			setAmount(amount);
		}

		Double gst = (Double)attributes.get("gst");

		if (gst != null) {
			setGst(gst);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long createdBy = (Long)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long modifiedBy = (Long)attributes.get("modifiedBy");

		if (modifiedBy != null) {
			setModifiedBy(modifiedBy);
		}
	}

	@Override
	public long getSupplierBillId() {
		return _supplierBillId;
	}

	@Override
	public void setSupplierBillId(long supplierBillId) {
		_supplierBillId = supplierBillId;
	}

	@Override
	public long getSupplierId() {
		return _supplierId;
	}

	@Override
	public void setSupplierId(long supplierId) {
		_columnBitmask |= SUPPLIERID_COLUMN_BITMASK;

		if (!_setOriginalSupplierId) {
			_setOriginalSupplierId = true;

			_originalSupplierId = _supplierId;
		}

		_supplierId = supplierId;
	}

	public long getOriginalSupplierId() {
		return _originalSupplierId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public String getSupplierBillNo() {
		if (_supplierBillNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _supplierBillNo;
		}
	}

	@Override
	public void setSupplierBillNo(String supplierBillNo) {
		_supplierBillNo = supplierBillNo;
	}

	@Override
	public String getSupplierBillDesc() {
		if (_supplierBillDesc == null) {
			return StringPool.BLANK;
		}
		else {
			return _supplierBillDesc;
		}
	}

	@Override
	public void setSupplierBillDesc(String supplierBillDesc) {
		_supplierBillDesc = supplierBillDesc;
	}

	@Override
	public String getSupplierBillType() {
		if (_supplierBillType == null) {
			return StringPool.BLANK;
		}
		else {
			return _supplierBillType;
		}
	}

	@Override
	public void setSupplierBillType(String supplierBillType) {
		_supplierBillType = supplierBillType;
	}

	@Override
	public Date getSupplierBillDate() {
		return _supplierBillDate;
	}

	@Override
	public void setSupplierBillDate(Date supplierBillDate) {
		_supplierBillDate = supplierBillDate;
	}

	@Override
	public double getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(double amount) {
		_amount = amount;
	}

	@Override
	public double getGst() {
		return _gst;
	}

	@Override
	public void setGst(double gst) {
		_gst = gst;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		_createdBy = createdBy;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			SupplierBill.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SupplierBill toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SupplierBill)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SupplierBillImpl supplierBillImpl = new SupplierBillImpl();

		supplierBillImpl.setSupplierBillId(getSupplierBillId());
		supplierBillImpl.setSupplierId(getSupplierId());
		supplierBillImpl.setCompanyId(getCompanyId());
		supplierBillImpl.setSupplierBillNo(getSupplierBillNo());
		supplierBillImpl.setSupplierBillDesc(getSupplierBillDesc());
		supplierBillImpl.setSupplierBillType(getSupplierBillType());
		supplierBillImpl.setSupplierBillDate(getSupplierBillDate());
		supplierBillImpl.setAmount(getAmount());
		supplierBillImpl.setGst(getGst());
		supplierBillImpl.setCreateDate(getCreateDate());
		supplierBillImpl.setCreatedBy(getCreatedBy());
		supplierBillImpl.setModifiedDate(getModifiedDate());
		supplierBillImpl.setModifiedBy(getModifiedBy());

		supplierBillImpl.resetOriginalValues();

		return supplierBillImpl;
	}

	@Override
	public int compareTo(SupplierBill supplierBill) {
		long primaryKey = supplierBill.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SupplierBill)) {
			return false;
		}

		SupplierBill supplierBill = (SupplierBill)obj;

		long primaryKey = supplierBill.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		SupplierBillModelImpl supplierBillModelImpl = this;

		supplierBillModelImpl._originalSupplierId = supplierBillModelImpl._supplierId;

		supplierBillModelImpl._setOriginalSupplierId = false;

		supplierBillModelImpl._setModifiedDate = false;

		supplierBillModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SupplierBill> toCacheModel() {
		SupplierBillCacheModel supplierBillCacheModel = new SupplierBillCacheModel();

		supplierBillCacheModel.supplierBillId = getSupplierBillId();

		supplierBillCacheModel.supplierId = getSupplierId();

		supplierBillCacheModel.companyId = getCompanyId();

		supplierBillCacheModel.supplierBillNo = getSupplierBillNo();

		String supplierBillNo = supplierBillCacheModel.supplierBillNo;

		if ((supplierBillNo != null) && (supplierBillNo.length() == 0)) {
			supplierBillCacheModel.supplierBillNo = null;
		}

		supplierBillCacheModel.supplierBillDesc = getSupplierBillDesc();

		String supplierBillDesc = supplierBillCacheModel.supplierBillDesc;

		if ((supplierBillDesc != null) && (supplierBillDesc.length() == 0)) {
			supplierBillCacheModel.supplierBillDesc = null;
		}

		supplierBillCacheModel.supplierBillType = getSupplierBillType();

		String supplierBillType = supplierBillCacheModel.supplierBillType;

		if ((supplierBillType != null) && (supplierBillType.length() == 0)) {
			supplierBillCacheModel.supplierBillType = null;
		}

		Date supplierBillDate = getSupplierBillDate();

		if (supplierBillDate != null) {
			supplierBillCacheModel.supplierBillDate = supplierBillDate.getTime();
		}
		else {
			supplierBillCacheModel.supplierBillDate = Long.MIN_VALUE;
		}

		supplierBillCacheModel.amount = getAmount();

		supplierBillCacheModel.gst = getGst();

		Date createDate = getCreateDate();

		if (createDate != null) {
			supplierBillCacheModel.createDate = createDate.getTime();
		}
		else {
			supplierBillCacheModel.createDate = Long.MIN_VALUE;
		}

		supplierBillCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			supplierBillCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			supplierBillCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		supplierBillCacheModel.modifiedBy = getModifiedBy();

		return supplierBillCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{supplierBillId=");
		sb.append(getSupplierBillId());
		sb.append(", supplierId=");
		sb.append(getSupplierId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", supplierBillNo=");
		sb.append(getSupplierBillNo());
		sb.append(", supplierBillDesc=");
		sb.append(getSupplierBillDesc());
		sb.append(", supplierBillType=");
		sb.append(getSupplierBillType());
		sb.append(", supplierBillDate=");
		sb.append(getSupplierBillDate());
		sb.append(", amount=");
		sb.append(getAmount());
		sb.append(", gst=");
		sb.append(getGst());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", modifiedBy=");
		sb.append(getModifiedBy());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.sphms.common.service.model.SupplierBill");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>supplierBillId</column-name><column-value><![CDATA[");
		sb.append(getSupplierBillId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supplierId</column-name><column-value><![CDATA[");
		sb.append(getSupplierId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supplierBillNo</column-name><column-value><![CDATA[");
		sb.append(getSupplierBillNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supplierBillDesc</column-name><column-value><![CDATA[");
		sb.append(getSupplierBillDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supplierBillType</column-name><column-value><![CDATA[");
		sb.append(getSupplierBillType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supplierBillDate</column-name><column-value><![CDATA[");
		sb.append(getSupplierBillDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>amount</column-name><column-value><![CDATA[");
		sb.append(getAmount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gst</column-name><column-value><![CDATA[");
		sb.append(getGst());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = SupplierBill.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			SupplierBill.class
		};
	private long _supplierBillId;
	private long _supplierId;
	private long _originalSupplierId;
	private boolean _setOriginalSupplierId;
	private long _companyId;
	private String _supplierBillNo;
	private String _supplierBillDesc;
	private String _supplierBillType;
	private Date _supplierBillDate;
	private double _amount;
	private double _gst;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private long _columnBitmask;
	private SupplierBill _escapedModel;
}